# configurations/contract_store_spam/nodes.toml

chain = "mantra-canary-net-1"
channel = "channel-0"
denom = "uom"
prefix = "mantra"
gas_per_byte = 50
base_gas = 200000
ibc_memo = "Contract store spam test"
memo = "Storing compiled contract with randomized memo"
ibc_memo_repeat = 10
rand_min = 15000
rand_max = 30000
revision_number = 4
timeout_height = 21720608
slip44 = 118
positions = 2                                       # Number of positions to use from the seed phrase
# 75000000
broadcast_mode = "grpc" # or "rpc"


msg_type = "instantiate_contract"

# [msg_params]

# # if this field is left blank as "", meteorite will send to random accounts endlessly
# to_address = ""
# amount = 1


# [msg_params]
# wasm_file = "artifacts/statefilestore.wasm"
# label = "statefilestore"

#msg_type = "instantiate_contract"

[msg_params]
code_id = 1
label = "statefilestore"
init_msg = '{}'
amount = 1000

[gas]
low = 25
precision = 3

[nodes]
rpc = ["https://rpc.canary.mantrachain.dev"]
api = "https://api.canary.mantrachain.dev"
grpc = "https://grpc.canary.mantrachain.dev"
